
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 114514
	#The name of the modpack
	modpackName = "Blue Archives Craft Pro"
	#The version of the modpack
	modpackVersion = "Beta 1.0.1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

